version: "3.9"
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=api-gateway
        - PORT=1101
    environment:
      - PORT=1101
    volumes:
      - "./config/docker.config.yaml:/app/config/config.yaml"
    ports:
      - "1101:1101"
    depends_on:
      - products
      - cart
      - order
      - postgres
      - consul

  products:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=products
        - PORT=8081
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - consul

  cart:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=cart
        - PORT=8082
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - consul
      - postgres

  order:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=order
        - PORT=8082
    environment:
      - PORT=8083
    ports:
      - "8083:8083"
    depends_on:
      - consul
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harsha
      POSTGRES_DB: services
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  consul:
    image: hashicorp/consul:1.11.2
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600"

volumes:
  postgres_data:
