-- Create "carts" table
CREATE TABLE "carts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY ("id"));
-- Create "orders" table
CREATE TABLE "orders" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY ("id"));
-- Create "products" table
CREATE TABLE "products" ("id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "price" real NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "users" table
CREATE TABLE "users" ("_id" uuid NOT NULL, "name" character varying NOT NULL, "username" character varying NOT NULL, "password" bytea NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("_id"));
