env: docker
gateway_server:
  port: 1101
Product_config:
  port: 8081
  host: products
cart_config:
  port: 8082
  host: cart
order_config:
  port: 8083
  host: order
user_config:
  port: 8091
  host: user